dist: bionic
language: generic
addons:
  apt:
    packages:
    - hash-slinger
install:
- git clone https://github.com/jwilk/exp509 ~/exp509
- make -C ~/exp509 install PREFIX=~/.local
script:
- private/check-cert
- private/check-ip
- private/check-wget
- private/check-tlsa
- private/check-wkd

# vim:ts=2 sts=2 sw=2 et
