dist: trusty
sudo: required
language: generic
services: docker
install:
- docker_packages='hash-slinger'
- sed -e "s/@PACKAGES@/$docker_packages/" .travis.docker > Dockerfile
- docker build -t ci .
- with_docker="docker run -v $PWD/private:/src ci sh -c"
- git clone https://github.com/jwilk/exp509 ~/exp509
- make -C ~/exp509 install PREFIX=~/.local
script:
- private/check-cert
- private/check-ip
- private/check-wget
- $with_docker /src/check-tlsa

# vim:ts=2 sts=2 sw=2 et
