#!/usr/bin/env bash

# Copyright © 2016-2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
echo 1..1
fprs=(
   CDB5A1243ACDB63009AD07212D4EB3A6015475F5
   C3F5C5D437F265B62D6F9ACF49A526BFE5874F63
)
tmpdir=$(mktemp -d -t jwilk.net.XXXXXX)
gpg2 --homedir "$tmpdir" --auto-key-locate wkd --locate-key 'jwilk@jwilk.net'
out=$(gpg2 --homedir "$tmpdir" --with-colons --list-keys | grep '^fpr:')
rm -rf "$tmpdir"
exp=$(printf 'fpr:::::::::%s:\n' "${fprs[@]}")
if [ "$out" = "$exp" ]
then
    echo 'ok 1'
else
    diff -u <(cat <<< "$exp") <(cat <<< "$out") | sed -e 's/^/# /'
    echo 'not ok 1'
fi

# vim:ts=4 sts=4 sw=4 et
