#!/bin/sh

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

if [ $# -eq 0 ]
then
    set -- http://jwilk.net
    set -- "$@" https://jwilk.net
fi
exec wget -O /dev/null "$@"

# vim:ts=4 sts=4 sw=4 et
