#!/usr/bin/env bash

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

tmpdir=$(mktemp -d -t jwilk.net.XXXXXX)
gpg2 --homedir "$tmpdir" --auto-key-locate wkd --locate-key 'jwilk@jwilk.net'
diff -u <(
    fmt='fpr:::::::::%s:\n'
    printf "$fmt" CDB5A1243ACDB63009AD07212D4EB3A6015475F5
    printf "$fmt" C3F5C5D437F265B62D6F9ACF49A526BFE5874F63
) <(gpg2 --homedir "$tmpdir" --with-colons --list-keys | grep '^fpr:')
rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
