#!/usr/bin/env bash

# Copyright © 2016-2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
echo 1..1
fprs=(
    7F5D0E9D3323F803D888C31EE1ABC877696EC74E
    71E4AC1CF2A89106B7ED17CA56F73257722B09D2
)
tmpdir=$(mktemp -d -t jwilk.net.XXXXXX)
gpg2 --homedir "$tmpdir" --auto-key-locate wkd --locate-key 'jwilk@jwilk.net'
out=$(gpg2 --homedir "$tmpdir" --with-colons --list-keys | grep '^fpr:')
rm -rf "$tmpdir"
exp=$(printf 'fpr:::::::::%s:\n' "${fprs[@]}")
if [ "$out" = "$exp" ]
then
    echo 'ok 1'
else
    diff -u <(cat <<< "$exp") <(cat <<< "$out") | sed -e 's/^/# /'
    echo 'not ok 1'
fi

# vim:ts=4 sts=4 sw=4 et
