#!/usr/bin/env bash

# Copyright © 2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
set -o pipefail
cd "${0%/*}/.."
hash_key()
{
    openssl pkey -outform der -pubout -pubin -in "$1" | openssl dgst -sha256 -binary | base64
}
pin1=$(hash_key tls/jwilk.net.1.pub)
pin2=$(hash_key tls/jwilk.net.2.pub)
printf 'Header always set Public-Key-Pins "pin-sha256=\\"%s\\"; pin-sha256=\\"%s\\"; max-age=2419200"\n' "$pin1" "$pin2"

# vim:ts=4 sts=4 sw=4 et
