#!/usr/bin/env bash

# Copyright © 2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
set -o pipefail
digest=$(openssl pkey -outform der -pubin -pubout -in tls/jwilk.net.1.pub | sha256sum)
printf '_443._tcp.jwilk.net. 3600 IN TLSA 1 1 1 %s\n' "${digest% *}"

# vim:ts=4 sts=4 sw=4 et
