#!/bin/sh

# Copyright © 2016-2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

exec whois jwilk.net \
| grep -Ev '^(>>> Last update of (WHOIS|whois) database:|# (local|gmt) time *:|# request from  *:)'

# vim:ts=4 sts=4 sw=4 et
