name: CI
on:
  push:
  pull_request:
  schedule:
  - cron: '51 7 * * 1'
jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install hash-slinger
      run:
        sudo apt-get install hash-slinger
    - name: install exp509
      run: |
        git clone https://github.com/jwilk/exp509 ~/exp509
        make -C ~/exp509 install PREFIX=~/.local
    - name: run checks
      run: |
        prove -v private/check-*
    - name: run shellcheck
      run: |
        shellcheck $(grep -l '#!.*sh$' private/*)

# vim:ts=2 sts=2 sw=2 et
