name: CI
on:
  push:
  pull_request:
  schedule:
  - cron: '51 7 * * 1'
jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install hash-slinger
      run:
        sudo apt-get install hash-slinger
    - name: install exp509
      run: |
        git clone https://github.com/jwilk/exp509 ~/exp509
        make -C ~/exp509 install PREFIX=~/.local
    - name: install ipdiff
      run: |
        git clone https://github.com/jwilk/ipdiff ~/ipdiff
        make -C ~/ipdiff install PREFIX=~/.local
    - name: run checks
      run: |
        prove -v private/check-*
    - name: run shellcheck
      run: |
        shellcheck $(grep -l '#!.*sh$' private/*)
    - name: run pydiatra
      run: |
        python3 -m pip install setuptools
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .

# vim:ts=2 sts=2 sw=2 et
