name: CI
on:
  push:
  pull_request:
  schedule:
  - cron: '51 7 * * 1'
jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install hash-slinger
      run:
        sudo apt-get install hash-slinger
    - name: install exp509
      run: |
        git clone https://github.com/jwilk/exp509 ~/exp509
        make -C ~/exp509 install PREFIX=~/.local
    - run: prove -v private/check-cert
    - run: prove -v private/check-ip
    - run: private/check-wget
    - run: prove -v private/check-tlsa
    - run: private/check-wkd
    - run: prove -v private/check-https-redir

# vim:ts=2 sts=2 sw=2 et
